In [1]:
from eegr import fit_bucket
from eegr import sim_data as sd

In [112]:
df_test_set('complex1').shape

(72, 4)

In [113]:
simple = df_test_set('simple')

In [117]:
simple['cat'].values[0]

'L_1_1'

In [109]:
def df_test_set(complexity):
    if complexity == 'simple':
        epoch_p = (1,2)
        time_p = (1,3,1)
        cat_p = [(1,1)]
        cont_p = [(1,1)]
        noise = (0,0)
        simple_df = sd.df_gen(epoch_p=epoch_p, time_p=time_p, 
                       cat_p=cat_p, cont_p=cont_p, noise_p=noise)
        return simple_df
    elif complexity == 'complex1':
        epoch_p = (1,5)
        time_p = (0,30,5)
        cat_p = [(1,1),(2,2),(3,3)]
        cont_p = [(1,3),(2,3)]
        noise = (2,3)
        cmplx1_df = sd.df_gen(epoch_p=epoch_p, time_p=time_p, 
                       cat_p=cat_p, cont_p=cont_p, noise_p=noise)
        return cmplx1_df
    elif complexity == 'complex2':
        epoch_p = (1,10)
        time_p = (0,100,10)
        cat_p = [(1,3),(2,5),(3,4)]
        cont_p = [(10,15),(20,30)]
        noise = (2.5,39)
        cmplx2_df = sd.df_gen(epoch_p=epoch_p, time_p=time_p, 
                       cat_p=cat_p, cont_p=cont_p, noise_p=noise)
        return cmplx2_df

In [79]:
def sample_df():
    epoch_p = (0,6)
    time_p = (0,8,1)
    cat_p = [(0,2), (5,7)]
    cont_p = [(0,1)]
    noise = (0,0)
    df = sd.df_gen(epoch_p=epoch_p, time_p=time_p, 
                   cat_p=cat_p, cont_p=cont_p, noise_p=noise)
    return epoch_p, time_p, cat_p, cont_p, df

In [31]:
epoch_idx = epochs.index.levels[epochs.index.names.index('Epoch_idx')].tolist()

In [33]:
epoch_idx
start, end = epoch_p
e = np.arange(start, end)
assert (epoch_idx == e).all

In [27]:
epoch_p, time_p, cat_p, cont_p, epochs = sample_df()
times = epochs.index.levels[epochs.index.names.index('Time')].tolist()
times

[0, 1, 2, 3, 4, 5, 6, 7]

In [28]:
start, end ,step = time_p
t = np.arange(start, end, step)
times = epochs.index.levels[epochs.index.names.index('Time')].tolist()
assert (times == t).all

In [19]:
assert (times == t).all

In [16]:
import numpy as np
start, end ,step = time_p
t = np.arange(start, end, step)

In [53]:
cont_p

[(0, 1)]

In [80]:
for i,range_set in enumerate(cont_p):
    start = range_set[0]
    end = range_set[1]
    col_label = 'cont_' + str(i+1) + '_range' + str(start) + ',' + str(end)
    assert ((epochs[col_label].values > start) & (epochs[col_label].values < end)).all

In [58]:
epochs.head()

cat  cont_1_range0,1  data
Index    Epoch_idx data_group Time                              
id_10001 0         testing1   0     L_0_2         0.645002   0.0
                              1     L_0_2         0.325309   2.0
                              2     L_0_2         0.364768   4.0
                              3     L_0_2         0.971212   6.0
                              4     L_0_2         0.873982   8.0

In [69]:
(np.tile(times,6) + 0) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14,  0,  2,  4,  6,  8, 10, 12, 14,  0,
        2,  4,  6,  8, 10, 12, 14,  0,  2,  4,  6,  8, 10, 12, 14,  0,  2,
        4,  6,  8, 10, 12, 14,  0,  2,  4,  6,  8, 10, 12, 14])

In [63]:
epochs[epochs['cat'] == 'L_0_2']['data'].values

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.,  0.,  2.,  4.,  6.,  8.,
       10., 12., 14.,  0.,  2.,  4.,  6.,  8., 10., 12., 14.,  0.,  2.,
        4.,  6.,  8., 10., 12., 14.,  0.,  2.,  4.,  6.,  8., 10., 12.,
       14.,  0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [81]:
# test if column matches cont_p range
def test_cat_p_match_data():
    epoch_p, time_p, cat_p, cont_p, epochs = sample_df()
    start, end = epoch_p
    for cat in cat_p:
        b0, b1 = cat[0], cat[1]
        want_arr = (np.tile(times, end - start) + b0) * b1
        label = 'L_' + str(b0) + '_' + str(b1)
        act_arr = epochs[epochs['cat'] == label]['data'].values
        assert (want_arr == act_arr).all

In [82]:
test_cat_p_match_data()

In [76]:
for cat in cat_p:
    b0, b1 = cat[0], cat[1]

In [73]:
test_cat_p_match_data()

In [49]:
col_label = 'cont_' + str(1) + '_range' + str(0) + ',' + str(1)
col_label

'cont_1_range0,1'

In [45]:
assert ((epochs['cont_1_range0,1'].values > 0) & (epochs['cont_1_range0,1'].values < 1)).all

In [83]:
LHS = ["data"]
RHS = "cat"
fit_grids = fit_bucket.make_fit_table(epochs,LHS,RHS)

subid: testing1


/usr/local/anaconda3/lib/python3.6/site-packages/statsmodels/stats/outliers_influence.py:309: RuntimeWarning: invalid value encountered in true_divide
  return  self.results.resid / sigma / np.sqrt(1 - hii)
/usr/local/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
/usr/local/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
/usr/local/anaconda3/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)


In [84]:
fit_grids[0]['fit']['ci'].shape

(8, 1, 1, 2)

In [97]:
values = (np.tile(times,1) + 0) * 2

In [107]:
for i, val in enumerate(values): 
    print(i, val)
    break

0 0


In [108]:
for i, val in enumerate(values): 
    assert(fit_grids[0]['fit']['ci'][i][0][0] == [val,val]).all()

In [12]:
assert(fit_grids[0]['fit']['ci'][0][0][0] == [0,0]).all()

In [92]:
fit_grids[0]['fit']['ci'][:]

array([[[[ 0.,  0.]]],


       [[[ 2.,  2.]]],


       [[[ 4.,  4.]]],


       [[[ 6.,  6.]]],


       [[[ 8.,  8.]]],


       [[[10., 10.]]],


       [[[12., 12.]]],


       [[[14., 14.]]]], dtype=float32)